precioManzana = float(input('Dime el precio de la manzana: '))
cantidadManzana = float(input('Dime la cantidad de manzanas vendidas: '))
print("Hola buenas tardes")
print("total: ")
print("Total: " , precioManzana * cantidadManzana)
print("Total: " + str(precioManzana * cantidadManzana))
print(f"Total: {precioManzana * cantidadManzana}" )
